"""Generate the firmware public-key header from the owner's PEM public key."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


def _public_point(public_key_path: Path) -> bytes:
    try:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import ec
    except ImportError as error:
        raise SystemExit(
            "cryptography is required; install tools/firmware_signing/requirements-firmware-signing.txt"
        ) from error
    key = serialization.load_pem_public_key(public_key_path.read_bytes())
    if not isinstance(key, ec.EllipticCurvePublicKey) or not isinstance(
        key.curve, ec.SECP256R1
    ):
        raise ValueError("public key must be ECDSA P-256 PEM")
    point = key.public_bytes(
        serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint
    )
    if len(point) != 65:
        raise ValueError("unexpected P-256 public point length")
    return point


def _header(key_id: str, point: bytes) -> str:
    if len(key_id.encode("ascii")) != 16:
        raise ValueError("key ID must be exactly 16 ASCII bytes")
    values = ", ".join(f"0x{value:02x}U" for value in point)
    return f'''#pragma once

#include <stdint.h>

/* Generated by tools/firmware_signing/provision_firmware_auth_key.py. */
#define CBV_FIRMWARE_AUTH_KEY_ID "{key_id}"
#define CBV_FIRMWARE_AUTH_PUBLIC_KEY {{ {values} }}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--public-key", type=Path, required=True)
    parser.add_argument("--key-id", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        args.output.write_text(_header(args.key_id, _public_point(args.public_key)), encoding="utf-8")
    except (OSError, ValueError) as error:
        print(f"provision_firmware_auth_key: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
